In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import MinMaxScaler

from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
import xgboost as xgb

In [ ]:
raw_data = pd.read_csv('Loan_status_2007-2020Q3.gzip', nrows=8*10**5, low_memory=False)

In [34]:
data_dictionary = pd.read_excel('LCDataDictionary.xlsx').dropna(axis=1, how='all', inplace=True)

In [35]:
data_dictionary

               LoanStatNew                                        Description
0           acc_now_delinq  The number of accounts on which the borrower i...
1     acc_open_past_24mths         Number of trades opened in past 24 months.
2               addr_state  The state provided by the borrower in the loan...
3                 all_util              Balance to credit limit on all trades
4               annual_inc  The self-reported annual income provided by th...
..                     ...                                                ...
148      settlement_amount  The loan amount that the borrower has agreed t...
149  settlement_percentage  The settlement amount as a percentage of the p...
150        settlement_term  The number of months that the borrower will be...
151                    NaN                                                NaN
152                    NaN  * Employer Title replaces Employer Name for al...

[153 rows x 2 columns]

In [4]:
len(raw_data)

800000

In [5]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Columns: 142 entries, Unnamed: 0 to debt_settlement_flag
dtypes: float64(106), int64(1), object(35)
memory usage: 866.7+ MB

In [29]:
df = raw_data.copy()
# first look of the data
df.head()

,Unnamed: 0,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag
0,0,1077501,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,1,1077430,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,2,1077175,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,3,1076863,10000.0,10000.0,10000.0,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,4,1075358,3000.0,3000.0,3000.0,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

In [31]:
df.columns

Index(['Unnamed: 0', 'id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date',
       'hardship_length', 'hardship_dpd', 'hardship_loan_status',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'debt_settlement_flag'],
      dtype='object', length=142)

In [32]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [37]:
for col in df.columns:
    description = data_dictionary.loc[data_dictionary['LoanStatNew'] == col, ['Description']]
    print(col + ': ' + description)

                                          Description
27  id: A unique LC assigned ID for the loan listing.
                                          Description
41  loan_amnt: The listed amount of the loan appli...
                                          Description
23  funded_amnt: The total amount committed to tha...
                                          Description
24  funded_amnt_inv: The total amount committed by...
                                          Description
94  term: The number of payments on the loan. Valu...
                            Description
34  int_rate: Interest Rate on the loan
                                          Description
33  installment: The monthly payment owed by the b...
                      Description
25  grade: LC assigned loan grade
                             Description
92  sub_grade: LC assigned loan subgrade
                                          Description
20  emp_title: The job title supplied by the Borro...
                                          Description
19  emp_length: Employment length in years. Possib...
                                          Description
26  home_ownership: The home ownership status prov...
                                         Description
4  annual_inc: The self-reported annual income pr...
                                           Description
112  verification_status: Indicates if income was v...
                                     Description
35  issue_d: The month which the loan was funded
                                Description
42  loan_status: Current status of the loan
                                          Description
88  pymnt_plan: Indicates if a payment plan has be...
                                     Description
111  url: URL for the LC page with listing data.
                                          Description
87  purpose: A category provided by the borrower f...
                                       Description
95  title: The loan title provided by the borrower
                                           Description
114  zip_code: The first 3 numbers of the zip code ...
                                         Description
2  addr_state: The state provided by the borrower...
                                          Description
16  dti: A ratio calculated using the borrowerâ€™s t...
                                          Description
13  delinq_2yrs: The number of 30+ days past-due i...
                                          Description
18  earliest_cr_line: The month the borrower's ear...
                                          Description
22  fico_range_low: The lower boundary range the b...
                                          Description
21  fico_range_high: The upper boundary range the ...
                                          Description
32  inq_last_6mths: The number of inquiries in pas...
                                          Description
50  mths_since_last_delinq: The number of months s...
                                          Description
52  mths_since_last_record: The number of months s...
                                          Description
73  open_acc: The number of open credit lines in t...
                                     Description
85  pub_rec: Number of derogatory public records
                                  Description
90  revol_bal: Total credit revolving balance
                                          Description
91  revol_util: Revolving line utilization rate, o...
                                          Description
99  total_acc: The total number of credit lines cu...
                                          Description
29  initial_list_status: The initial listing statu...
                                          Description
80  out_prncp: Remaining outstanding principal for...
                                          Description
81  out_prncp_inv: Remaining outstanding principal...
                                           Description
105  total_pymnt: Payments received to date for tot...
                                           Description
106  total_pymnt_inv: Payments received to date for...
                                     Description
109  total_rec_prncp: Principal received to date
                                  Description
107  total_rec_int: Interest received to date
                                        Description
108  total_rec_late_fee: Late fees received to date
                                   Description
89  recoveries: post charge off gross recovery
                                          Description
11  collection_recovery_fee: post charge off colle...
                                      Description
40  last_pymnt_d: Last month payment was received
                                          Description
39  last_pymnt_amnt: Last total payment amount rec...
                                  Description
58  next_pymnt_d: Next scheduled payment date
                                          Description
36  last_credit_pull_d: The most recent month LC p...
                                          Description
37  last_fico_range_high: The upper boundary range...
                                          Description
38  last_fico_range_low: The lower boundary range ...
                                          Description
12  collections_12_mths_ex_med: Number of collecti...
                                          Description
51  mths_since_last_major_derog: Months since most...
                                          Description
84  policy_code: publicly available policy_code=1\...
                                         Description
6  application_type: Indicates whether the loan i...
                                         Description
5  annual_inc_joint: The combined self-reported a...
                                          Description
17  dti_joint: A ratio calculated using the co-bor...
Empty DataFrame
Columns: [Description]
Index: []
                                         Description
0  acc_now_delinq: The number of accounts on whic...
                                         Description
96  tot_coll_amt: Total collection amounts ever owed
                                          Description
97  tot_cur_bal: Total current balance of all acco...
                                          Description
74  open_acc_6m: Number of open trades in last 6 m...
                                          Description
77  open_act_il: Number of currently active instal...
                                          Description
75  open_il_12m: Number of installment accounts op...
                                          Description
76  open_il_24m: Number of installment accounts op...
                                          Description
53  mths_since_rcnt_il: Months since most recent i...
                                           Description
101  total_bal_il: Total current balance of all ins...
                                          Description
28  il_util: Ratio of total current balance to hig...
                                          Description
78  open_rv_12m: Number of revolving trades opened...
                                          Description
79  open_rv_24m: Number of revolving trades opened...
                                          Description
43  max_bal_bc: Maximum current balance owed on al...
                                       Description
3  all_util: Balance to credit limit on all trades
Empty DataFrame
Columns: [Description]
Index: []
                                     Description
30  inq_fi: Number of personal finance inquiries
                               Description
103  total_cu_tl: Number of finance trades
                                          Description
31  inq_last_12m: Number of credit inquiries in pa...
                                         Description
1  acc_open_past_24mths: Number of trades opened ...
                                         Description
7  avg_cur_bal: Average current balance of all ac...
                                         Description
8  bc_open_to_buy: Total open to buy on revolving...
                                         Description
9  bc_util: Ratio of total current balance to hig...
                                          Description
10  chargeoff_within_12_mths: Number of charge-off...
                                          Description
14  delinq_amnt: The past-due amount owed for the ...
                                          Description
45  mo_sin_old_il_acct: Months since oldest bank i...
                                          Description
46  mo_sin_old_rev_tl_op: Months since oldest revo...
                                          Description
47  mo_sin_rcnt_rev_tl_op: Months since most recen...
                                          Description
48  mo_sin_rcnt_tl: Months since most recent accou...
                               Description
49  mort_acc: Number of mortgage accounts.
                                          Description
54  mths_since_recent_bc: Months since most recent...
                                          Description
55  mths_since_recent_bc_dlq: Months since most re...
                                          Description
56  mths_since_recent_inq: Months since most recen...
                                          Description
57  mths_since_recent_revol_delinq: Months since m...
                                          Description
59  num_accts_ever_120_pd: Number of accounts ever...
                                          Description
60  num_actv_bc_tl: Number of currently active ban...
                                          Description
61  num_actv_rev_tl: Number of currently active re...
                                          Description
62  num_bc_sats: Number of satisfactory bankcard a...
                               Description
63  num_bc_tl: Number of bankcard accounts
                                  Description
64  num_il_tl: Number of installment accounts
                                         Description
65  num_op_rev_tl: Number of open revolving accounts
                                    Description
66  num_rev_accts: Number of revolving accounts
                                          Description
67  num_rev_tl_bal_gt_0: Number of revolving trade...
                                  Description
68  num_sats: Number of satisfactory accounts
                                          Description
69  num_tl_120dpd_2m: Number of accounts currently...
                                          Description
70  num_tl_30dpd: Number of accounts currently 30 ...
                                          Description
71  num_tl_90g_dpd_24m: Number of accounts 90 or m...
                                          Description
72  num_tl_op_past_12m: Number of accounts opened ...
                                          Description
82  pct_tl_nvr_dlq: Percent of trades never delinq...
                                          Description
83  percent_bc_gt_75: Percentage of all bankcard a...
                                          Description
86  pub_rec_bankruptcies: Number of public record ...
                       Description
93  tax_liens: Number of tax liens
                                        Description
98  tot_hi_cred_lim: Total high credit/credit limit
                                           Description
100  total_bal_ex_mort: Total credit balance exclud...
                                           Description
102  total_bc_limit: Total bankcard high credit/cre...
                                           Description
104  total_il_high_credit_limit: Total installment ...
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
                                           Description
123  sec_app_open_act_il:  Number of currently acti...
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
Empty DataFrame
Columns: [Description]
Index: []
                                           Description
128  hardship_flag: Flags whether or not the borrow...
                                           Description
129  hardship_type: Describes the hardship plan off...
                                           Description
130  hardship_reason: Describes the reason the hard...
                                           Description
131  hardship_status: Describes if the hardship pla...
                                           Description
132  deferral_term: Amount of months that the borro...
                                           Description
133  hardship_amount: The interest payment that the...
                                           Description
134  hardship_start_date: The start date of the har...
                                           Description
135  hardship_end_date: The end date of the hardshi...
                                           Description
136  payment_plan_start_date: The day the first har...
                                           Description
137  hardship_length: The number of months the borr...
                                           Description
138  hardship_dpd: Account days past due as of the ...
                                           Description
139  hardship_loan_status: Loan Status as of the ha...
                                           Description
140  orig_projected_additional_accrued_interest: Th...
                                           Description
141  hardship_payoff_balance_amount: The payoff bal...
                                           Description
142  hardship_last_payment_amount: The last payment...
                                           Description
144  debt_settlement_flag: Flags whether or not the...

In [33]:
df.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,...,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount
count,799999.000000,799999.000000,799999.000000,799999.000000,7.999950e+05,798802.000000,799970.000000,799999.000000,799999.000000,799970.000000,...,78173.000000,78173.000000,78173.000000,38505.000000,50057.000000,38505.000000,38505.000000,49388.000000,50057.000000,50057.000000
mean,15055.474632,15040.625457,14998.811556,446.302416,7.687778e+04,18.638795,0.249751,703.589517,707.589794,0.581033,...,12.563251,0.051322,0.082919,2.236437,134.224838,2.236437,2.447111,274.895998,8861.762172,736.459892
std,9529.079615,9524.089313,9538.649051,274.433662,1.431359e+05,17.669143,0.771159,34.972372,34.973498,0.902730,...,8.167618,0.443244,0.430156,0.581537,264.020272,0.581537,6.281336,383.434241,7428.900566,1808.580215
min,500.000000,500.000000,0.000000,4.930000,0.000000e+00,0.000000,0.000000,610.000000,614.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8000.000000,8000.000000,8000.000000,246.000000,4.500000e+04,11.230000,0.000000,675.000000,679.000000,0.000000,...,7.000000,0.000000,0.000000,2.000000,0.000000,2.000000,0.000000,56.860000,2787.390000,261.570000
50%,12050.000000,12000.000000,12000.000000,375.820000,6.500000e+04,17.220000,0.000000,695.000000,699.000000,0.000000,...,11.000000,0.000000,0.000000,2.000000,0.000000,2.000000,0.000000,160.250000,7106.490000,424.160000
75%,20000.000000,20000.000000,20000.000000,596.680000,9.199200e+04,23.910000,0.000000,720.000000,724.000000,1.000000,...,17.000000,0.000000,0.000000,2.000000,167.170000,2.000000,0.000000,362.481225,13362.860000,688.930000
max,40000.000000,40000.000000,40000.000000,1719.830000,1.100000e+08,999.000000,58.000000,845.000000,850.000000,33.000000,...,106.000000,21.000000,23.000000,4.000000,2000.000000,4.000000,82.000000,8702.110000,40306.410000,31276.010000

In [25]:
df['loan_status'].value_counts()

Fully Paid                                             411473
Current                                                272075
Charged Off                                            104007
Late (31-120 days)                                       5476
In Grace Period                                          3226
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                         881
Does not meet the credit policy. Status:Charged Off       761
Default                                                   112
Name: loan_status, dtype: int64

In [26]:
df['loan_status'].unique()

array(['Fully Paid', 'Charged Off', nan,
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off', 'Current',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Default'], dtype=object)

In [10]:
def get_missing_data_info(dataframe):
    total = dataframe.isnull().sum().sort_values(ascending=False)
    percent_1 = dataframe.isnull().sum() / dataframe.isnull().count()*100
    percent_2 = (round(percent_1,1)).sort_values(ascending=False)
    missing_data = pd.concat([total, percent_2], axis=1, keys=['Total', '%'])
    missing_data = missing_data[missing_data['Total'] > 0]
    return missing_data

In [20]:
missing_data = get_missing_data_info(df)
missing_data = missing_data[missing_data['%'] > 50]
missing_data

Empty DataFrame
Columns: [Total, %]
Index: []

In [15]:
missing_data.index

Index(['hardship_loan_status', 'hardship_reason', 'hardship_status',
       'hardship_type', 'deferral_term', 'hardship_dpd', 'hardship_length',
       'payment_plan_start_date', 'hardship_end_date', 'hardship_start_date',
       'orig_projected_additional_accrued_interest',
       'hardship_last_payment_amount', 'hardship_payoff_balance_amount',
       'hardship_amount', 'verification_status_joint', 'sec_app_revol_util',
       'revol_bal_joint', 'dti_joint', 'sec_app_inq_last_6mths',
       'sec_app_earliest_cr_line', 'sec_app_fico_range_high',
       'sec_app_open_act_il', 'sec_app_fico_range_low',
       'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med', 'annual_inc_joint',
       'sec_app_open_acc', 'sec_app_mort_acc', 'mths_since_last_record',
       'mths_since_recent_bc_dlq', 'mths_since_last_major_derog',
       'mths_since_recent_revol_delinq', 'next_pymnt_d',
       'mths_since_last_delinq', 'il_util', 'mths_since_rcnt_il', 'all_util',
       'total_cu_tl', 'open_il_24m', 'open_il_12m', 'open_act_il',
       'open_acc_6m', 'open_rv_12m', 'open_rv_24m', 'total_bal_il', 'inq_fi',
       'max_bal_bc', 'inq_last_12m'],
      dtype='object')

In [18]:
len(missing_data)

49

In [16]:
df.drop(missing_data.index, axis=1, inplace=True)

In [17]:
df.shape

(800000, 93)

In [19]:
get_missing_data_info(df)

                        Total     %
mths_since_recent_inq  139583  17.4
mo_sin_old_il_acct      96854  12.1
num_tl_120dpd_2m        91345  11.4
pct_tl_nvr_dlq          70431   8.8
avg_cur_bal             70324   8.8
...                       ...   ...
total_pymnt                 1   0.0
out_prncp_inv               1   0.0
out_prncp                   1   0.0
initial_list_status         1   0.0
revol_bal                   1   0.0

[91 rows x 2 columns]